### PR TITLE
Biggest compositor pr i think,(for now)

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by Froxcey** [comment]
Awesome, will take a look

vibe

**Review by Sammy99jsp — APPROVED** [review]
Woaah!
Looks f**king awesome to me.

**Review by Froxcey — APPROVED** [review]
Learly idk what I'm reviewing, but it runs well so LGTM. I will read it in detail over the next few days to, you know, run rust. 

vibe

**Review by MrSerge01 — APPROVED** [review]
WOOOOOOO LETS GOOOOOOOOOO

LFGTM (what just Sammy said)
-The Goos.

**Review by SunightMC — APPROVED** [review]
OMG so awesome :)

**Comment by Froxcey** [comment]
Imma merge it now

**Pull request merged**
