### PR TITLE
Better file organization

### PR DESCRIPTION
**Pull request by akane6704**

### CODE REVIEW

**Review by froxcey — APPROVED** [review]
Good, I guess? Yeah, LGTM.

**Review by StoneMcYT — APPROVED** [review]
Hello Akane,
this looks good to me! Lovely work as usal keep it up.
Many thanks,
Stone himself
Head Manger @ AvdanOS

**Comment by akane6704** [comment]
<3

**Comment by akane6704** [comment]
<3

**Comment by akane6704** [comment]
Mmmh btw i'm merging since you approved

**Pull request merged**
