### PR TITLE
Config file progress.

### PR DESCRIPTION
**Pull request by dorakuflu**
Created config file, added keybinds for the tiling mode of the WM (not functional yet), modified build file to copy config.

### CODE REVIEW

**Comment by akane6704** [comment]
> Created config file, added keybinds for the tiling mode of the WM (not functional yet), modified build file to copy config.

Interesting but we're making a floating wm, not a tiling. Tiling wm for now it's optional, we don't really need keybindings if there's not a base

**Comment by akane6704** [comment]
Btw the rest looking good

**Comment by dorakuflu** [comment]
> > Created config file, added keybinds for the tiling mode of the WM (not functional yet), modified build file to copy config.
> 
> Interesting but we're making a dynamic wm, not a tiling. Tiling wm for now it's secondary we don't really need keybindings if there's not a base

I mean it doesn't hurt anybody does it? I don't think just having them in the config file until we build a base for it would affect production in any way. I appreciate the feedback.

**Review by akane6704 — APPROVED** [review]
Alright

**Review by MrSerge01 — APPROVED** [review]
I can't understand anything sadly, but

LGTM,
-The Goos.

**Pull request merged**
