### PR TITLE
Comments and slight changes in winit.rs

### PR DESCRIPTION
**Pull request by Kibalchish47**
Not much mostly just import comments and slight changes to the said imports

### CODE REVIEW

**Review by Sammy99jsp — CHANGES_REQUESTED** [review]
I'm not sure if comments on imports are strictly necessary, but I'll have @akane6704 check this.

**Comment by akane6704** [comment]
Why modify shell::xdg? Also i think it's pretty fine

**Comment by akane6704** [comment]
Okay now i think it's all good

**Review by akane6704 — APPROVED** [review]

**Comment by akane6704** [comment]
@Sammy99jsp merge?

**Review by Sammy99jsp — APPROVED** [review]
LGTM!

**Pull request merged**
