### PR TITLE
AvdanOS Configuration Pt. II 

### LINKED ISSUE #46: Compositor Configuration: AvConfig macro
Use a macro to declare Configuration entries:
```rust
#[AvConfig({
    // Example config macro from #23 
    "Change focus to the nth window in the taskbar."
    window(d)       => (Super+{d}),
})]
pub struct Keybinds;
```

This would automatically generate a struct to represent the raw values of this section,
which `serde-json` can then parse.

Additionally, it could add some additional parsing unitl we reach the section's final struct.

```rust
impl ConfigurationSection for Keybinds {
    type Raw = HashMap<String, Any>;
    
    fn parse(...) {
        /* .  .  . */
    }
}
```

This macro would then generate a default config file (from the source itself).

Additionally, this macro could also export a JSON Schema upon compile, which can then be linked with CI to be put somewhere (e.g. `https://files.avdanos.org/compositor/schema.json`).

## Proposed Syntax
The first parameter in the macro contains the config item declarations.

### A single item
Each item declaration contains:
- a description
- an identifier
- a default value

```rust
{
    "An example item"
    identifier() => "Hello World"
}
```

### Support for config 'macros'
Custom key shortcut syntax:

```rust
{
    "Close active window"
    closeWindow() => (Alt+F4),

    "Switch to workspace `d`"
    workspace(d) => (Ctrl+Logo+{d}),
}
```

### PR DESCRIPTION
**Pull request by Sammy99jsp**
Associated Issues: #46 #23 

The main changes are the continuation of the custom Syntax from my first repo.

## Adding a custom section 

Now, implementing a configuration section is as simple as:
1. Declaring it:
```rust
use compositor_macros::config_section;

use crate::config::ConfigurationSection;

config_section!(
    MyCustomSection {
        "How many horns does a unicorn have?"
        unicornHorns => 1,
    }
);

impl ConfigurationSection for MyCustomSection {
    const PATH : &'static str = "$.myCustomSection";
}
```

2. Adding it to the `Config` struct somewhere:
```rust
#[derive(Deserialize, Debug)]
pub struct Config {
    /* . . . . */
    pub my_custom_section: MyCustomSection
}
```
And that's it!

## Using the Config

The config can be gotten anywhere after initialization with `Config::config()`.
Paths are also accessible if they are declared appropriately in their sections:
```rust
let config = Config::config();
println!("Horns on a unicorn: {}", config.my_custom_section.unicornHorns);
```

## Future plans
- Config macros automatically generate JSON Schemas, and default JSONC sections.
- Build script packages them together, to be bundled with a release.

### CODE REVIEW

**Review by Froxcey — APPROVED** [review]
LGTM, learned a lot from this

vibe

**Review by Froxcey — APPROVED** [review]
LGTM

vibe

**Comment by Froxcey** [comment]
lmao I thought my review didn't sent

**Comment by MrSerge01** [comment]
lmao

**Comment by MrSerge01** [comment]
@Sammy99jsp btw, if you have more work to do with this, it's great to make this a draft PR

**Pull request merged**
