### PR TITLE
Implementing the wayland client

### PR DESCRIPTION
**Pull request by akane6704**

### CODE REVIEW

**Comment by akane6704** [comment]
Note: this is only an initial commit, so this need to be worked on more

**Review by froxcey — APPROVED** [review]
Me understanding nothing: LGTM!

vibe

**Review by MrSerge01 — APPROVED** [review]
Same opinion as Froxcey.

LGTM,
-The Goos.

**Review by Sammy99jsp — APPROVED** [review]
LGTM

**Pull request merged**
