### PR TITLE
Better readibility

### PR DESCRIPTION
**Pull request by akane6704**

### CODE REVIEW

**Review by MrSerge01 — APPROVED** [review]
LGTM,
-The Goos.

(why did you fork it another time? merge conflict? :trollface: )

**Review by froxcey — APPROVED** [review]
Thx, LGTM!
vibe

**Comment by akane6704** [comment]
> LGTM, -The Goos.
> 
> (why did you fork it another time? merge conflict? :trollface: )

Bc i accidentally deleted the dev branch on my fork

**Review by Sammy99jsp — APPROVED** [review]
Pretty

**Pull request merged**
