### PR TITLE
Updated The TODO List

### PR DESCRIPTION
**Pull request by Rohith0009**
Updated The TODO List

### CODE REVIEW

**Comment by akane6704** [comment]
What are these big grammar mistakes in README.md + the wayland client is not completed

**Comment by Rohith0009** [comment]
> What are these big grammar mistakes in README.md + the wayland client is not completed

ok I marked the wayland client as ❌ but what are the big grammar mistakes?

**Comment by akane6704** [comment]
The wayland client is being worked on, also you misspelled refer incorrectly

**Comment by Rohith0009** [comment]
> The wayland client is being worked on, also you misspelled refer incorrectly

oops sorry

**Comment by akane6704** [comment]
> > What are these big grammar mistakes in README.md + the wayland client is not completed
> 
> ok I marked the wayland client as ❌ but what are the big grammar mistakes?

Well, i think see and refer don't make that much difference

**Comment by Rohith0009** [comment]
> Well, i think see and refer don't make that much difference

'refer' is formal.

**Comment by akane6704** [comment]
How see is informal lmao

**Comment by Rohith0009** [comment]
> How see is informal lmao

ok now should I use 'see' or 'refer'

**Comment by akane6704** [comment]
Leave it as it is now

**Comment by Rohith0009** [comment]
> Leave it as it is now

ok then

**Review by akane6704 — APPROVED** [review]
Perfect

**Review by froxcey — CHANGES_REQUESTED** [review]
Please ONLY commit to dev branch. All the readme info will get merged to main soon. 

Tbh refer sounds like a better word choice to me.

Also, both the PR and current version doesn't follow the markdown format. `- [ ] ` is for a empty checkbox, and ` - [x] ` is for a ticked checkbox. Please consider using those markdown features instead of unstandardised `- [ - ] ` or emojis.

**Comment by Rohith0009** [comment]
> Tbh refer sounds like a better word choice to me.

Yep!

**Comment by Rohith0009** [comment]
> Please ONLY commit to dev branch. All the readme info will get merged to main soon.

ok

**Comment by akane6704** [comment]
They're meanings are kinda different tho

**Comment by froxcey** [comment]
Again, please only make PRs targeting **dev branch**, closing this now.

**Comment by akane6704** [comment]
Just leave it alone

**Pull request closed without merging**
