### PR TITLE
Re-structuring, Constants, Build Script, support for JSON with Comments, Some implementation of #31 

### PR DESCRIPTION
**Pull request by Sammy99jsp**
See individual commits for more info.

### CODE REVIEW

**Comment by Sammy99jsp** [comment]
Sorry for commenting out your code, @akane6704.
That was supposed to be temporary.

**Review by froxcey — APPROVED** [review]
Very pro config loader, LGTM

vibe

**Comment by MrSerge01** [comment]
> ~~Sorry for commenting out your code, @akane6704.~~
> That was supposed to be temporary. 
> 
> I guess I didn't, soz for tag.

brutal

**Comment by MrSerge01** [comment]
BUT NOT ME???1!??!?!1!?1!?!1?1!1!!1!?1!?1!

**Review by MrSerge01 — APPROVED** [review]
:OOO

LGTM,
-The Goos.

**Review by akane6704 — APPROVED** [review]

**Comment by akane6704** [comment]
Merging

**Pull request merged**
