### PR TITLE
Updated wayland client

### PR DESCRIPTION
**Pull request by akane6704**
Added useful comments and got something working

### CODE REVIEW

**Review by MrSerge01 — APPROVED** [review]
Wow that is really cool 👍

LGTM,
-The Goos.

**Review by froxcey — APPROVED** [review]
Ye I was looking at this piece of code confused, like were we making a wayland client or server? Anyways, LGTM ^-^

**Comment by LucasoDevDotTk** [comment]
I know this doesn't really matter, but just some minor inconsistencies in spacing between comments + variables, could probably be fixed with a simple formatted run. (Line n. 9-12). 

Otherwise it's LGTM. 👍

**Review by Sammy99jsp — APPROVED** [review]
LGTM

**Pull request merged**
