### PR TITLE
REFACTOR: Basing compositor code off `smithay/anvil` now.

### PR DESCRIPTION
**Pull request by Sammy99jsp**
* Config directory changed to meet XDG spec: https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html
* Some Backend Generic-ising;
* Next PR should be a major refactor of `crate::compositor` to be in line with Simthay's `anvil` reference

### CODE REVIEW

**Comment by Trynera** [comment]
bro merge it

**Comment by Trynera** [comment]
jk

**Comment by Sammy99jsp** [comment]
So, yh. We seem to be running again.
Weirdly enough, now only launching from a `tty` is supported, lmao.
It does both compile and actually run, at least on my machine lol.

**Comment by MrSerge01** [comment]
why not request my review? 😭😭

**Review by MrSerge01 — APPROVED** [review]
I don't understand anything, but if it compiles and it gives progress, i LGTM it.

-The Goos.

**Comment by Froxcey** [comment]
Sorry, it took me a while to test build stuff. Hemm it doesn't build on my machine...
[Bare-metal build](https://pastebin.com/PFcxPqWH) | [Container build](https://github.com/Avdan-OS/Compositor/files/10529004/build.log)
vibe

**Comment by Sammy99jsp** [comment]
Huh;
In that case, I'll check later today -- it could be that either I've missed some commits, or something else. Thanks.

**Comment by MrSerge01** [comment]
weird

**Comment by Froxcey** [comment]
I'll try looking into it, but I can only do so much.

**Comment by Froxcey** [comment]
I think it's better to move this to a new issue. 
#65

**Pull request merged**
