### PR TITLE
Updated contributing.md

### PR DESCRIPTION
**Pull request by Rohith0009**
Updated contributing.md by adding more documentation, updated bug_report.md and readme.md

# Contributing.md Looks Like This:

# Contributing Guideline

## Basics

To start your contribution, please follow the steps below:

1. Create a fork of this repo

2. Git clone your fork to your machine

```sh
git clone url://to.your/github/fork.git
```

3. Use dev branch, commits targetting main will be ignored.

```sh
git checkout -b dev remotes/upstream/dev
```

4. Make changes as you want

5. Commit your changes

```sh
git commit -m "concise message of the change"
```

`Tip: you can set up code signing and add -S to the commit command above to get a verified check mark`

6. Push your changes

```sh
git push
```

7. Create pull request on GitHub

No Direct Commits

Follow the [Rust Styling Guideline](https://docs.avdanos.com/docs/contributing/development/code_guidelines/rust_guidelines)

### CODE REVIEW

**Comment by froxcey** [comment]
Any contribution to main branch will be ignored? Maybe not this one? If then, I will add a LGTM.

**Comment by Rohith0009** [comment]
> Any contribution to main branch will be ignored? Maybe not this one? If then, I will add a LGTM.

I Commited to main because the bug_report was not on the dev branch it was only on the main branch otherwise I will do only to the dev branch

**Review by froxcey — APPROVED** [review]
LGTM

(No sticker cuz on mobile)

**Review by akane6704 — APPROVED** [review]
Merging

**Pull request merged**
