### PR TITLE
Fixed links in readme.md

### PR DESCRIPTION
**Pull request by Rohith0009**
^ title

### CODE REVIEW

**Review by froxcey — APPROVED** [review]
LGTM

**Comment by Rohith0009** [comment]
Could you merge It?

**Comment by froxcey** [comment]
Two reviews are required

**Comment by Rohith0009** [comment]
> Two reviews are required

oh ok

**Review by TechStudent11 — APPROVED** [review]
LGTM

**Review by Sammy99jsp — APPROVED** [review]
✅

**Comment by Rohith0009** [comment]
> LGTM

@TechStudent11 How did you approve these changes

**Pull request merged**
